[tichecker]
# 下游 tidb 数据库链接串
dsn = "marvin:marvin@tcp(192.168.2.90:5000)/?charset=utf8mb4"
# 检查下游 tidb 目标表 schema
schema = "dm_marvin"
# 检查下游 tidb 目标表列表
tables = ["t_marvin"]
# 检查表基于该字段划分范围检查，检查失败会按要求重试
# 该字段需要是个范围值
# 1、建议使用全局唯一的字段，比如：时间或者全局 ID、全局 UUID 等字段
# 2、非全局也是可以，比如：ID,NAME 联合主键，使用 ID 字段，但是可能会比较粗暴
base-table-column = "id"
# 检查表字段 base-table-column 是否存在索引且位于前缀，用于排序
is-index-column = false
# 检查表切分行数，尽可能小，会相对检查更准，但是不建议太小，否则大表会检查很久
split-table-rows = 2000
# tichecker 并发数
worker-threads = 4
# 检查失败重试等待间隔，单位：秒
time-sleep = 10
# 检查失败重试次数
check-retry = 10

[inspector]
# 表配置文件模板存放位置,用于读取
# 需要手工创建目录以及按命名格式创建并修改模板文件
# 文件名格式：table_diff.tmpl
config-template-dir = "/home/tidb/marvin/topology/dm/template"

# 表配置文件输出位置 - 不能更改
# 输出文件名格式：table_dir/table_diff{{i}}.toml
config-output-dir = "/home/tidb/marvin/topology/dm/output"

# 表检查结果输出目录 - 不能更改
# 输出文件名格式：table_dir/table_fixed{{i}}.sql
fix-sql-dir = "/home/tidb/marvin/topology/dm/fixed"

# diff 二进制检查线程
check-thread-count = 8
# sync-diff-inspector 根据主键／唯一键／索引将数据划分为多个 chunk，
# 对每一个 chunk 的数据进行对比。使用 chunk-size 设置 chunk 的大小
chunk-size = 1000